name: CI-CD Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set image tag
        id: tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push Frontend
        run: |
          pwd
          ls
          cd Application-Code/frontend/
          ls
          pwd
          docker build -t sajli/three-tier-frontend:${{ steps.tag.outputs.TAG }} .
          docker push sajli/three-tier-frontend:${{ steps.tag.outputs.TAG }}

      - name: Build & Push Backend
        run: |
          pwd
          cd Application-Code/backend/
          ls
          pwd
          docker build -t sajli/three-tier-backend:${{ steps.tag.outputs.TAG }} .
          docker push sajli/three-tier-backend:${{ steps.tag.outputs.TAG }}

      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v3

      - name: Deploy using Octopus
        run: |
          octo create-release \
            --project "k8s-poc" \
            --deployTo "development" \
            --server ${{ secrets.OCTOPUS_URL }} \
            --apiKey ${{ secrets.OCTOPUS_API_KEY }} \
            --variable "Frontend.Image.Tag=${{ steps.tag.outputs.TAG }}" \
            --variable "Backend.Image.Tag=${{ steps.tag.outputs.TAG }}"
