name: Continuous Build and Push

on:
  release:
    types:
      - created
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set image tag from GitHub release
        id: tag
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Build & Push Frontend
        run: |
          cd Application-Code/frontend
          docker build -t sajli/three-tier-frontend:${{ steps.tag.outputs.TAG }} .
          docker push sajli/three-tier-frontend:${{ steps.tag.outputs.TAG }}

      - name: Build & Push Backend
        run: |
          cd Application-Code/backend
          docker build -t sajli/three-tier-backend:${{ steps.tag.outputs.TAG }} .
          docker push sajli/three-tier-backend:${{ steps.tag.outputs.TAG }}

      # - name: Install Octopus CLI
      #   uses: OctopusDeploy/install-octopus-cli-action@v3

      # # - name: Deploy using Octopus
      # #   run: |
      # #     octo create-release \
      # #       --project "poc_k8s" \
      # #       --deployTo "development" \
      # #       --server ${{ secrets.OCTOPUS_URL }} \
      # #       --apiKey ${{ secrets.OCTOPUS_API_KEY }} \
      # #       --variable "Frontend.Image.Tag=${{ steps.tag.outputs.TAG }}" \
      # #       --variable "Backend.Image.Tag=${{ steps.tag.outputs.TAG }}"
      # - name: Login to Octopus
      #   uses: OctopusDeploy/login@v1
      #   with:
      #     server: ${{ secrets.OCTOPUS_URL }}
      #     api_key: ${{ secrets.OCTOPUS_API_KEY }}

      # # Create Octopus Release
      # - name: Create Release
      #   id: create_release
      #   uses: OctopusDeploy/create-release-action@v3
      #   with:
      #     project: poc_k8s
      #     space: Default
      #     variables: |
      #       Frontend.Image.Tag=${{ steps.tag.outputs.TAG }}
      #       Backend.Image.Tag=${{ steps.tag.outputs.TAG }}

      # # Deploy Release to Kubernetes
      # - name: Deploy Release
      #   uses: OctopusDeploy/deploy-release-action@v3
      #   with:
      #     project: poc_k8s
      #     space: Default
      #     release_number: ${{ steps.create_release.outputs.release_number }}
      #     environments: development
